### PR TITLE
Stop periodic calls

### LINKED ISSUE #1232: bug: ArdupilotManager keeps on requesting banners until the tab is closed/refreshed after flashing firmware
### Bug description

image

### Steps to reproduce

 - Flash navigator firmware
 - check messages in QGC

### Primary pain point(s)

it is VERY annoying

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

### PR DESCRIPTION
**Pull request by Williangalvani**
should fix #1232 and possibly others

### CODE REVIEW

File: core/frontend/src/utils/helper_functions.ts [hunk 1]
```diff
@@ -1,20 +1,46 @@
...
+
 /* Call a given function periodically for a given interval. */
 /**
  * @param func - Function to be called.
  * @param interval - Time in milliseconds to wait after the previous request is done
+ * @param func_name - Function name for tracking purposes
 * */
-export async function callPeriodically(func: () => Promise<void>, interval: number): Promise<void> {
+export async function callPeriodically(
+  func: () => Promise<void>, interval: number, func_name: string, automated_call?: boolean,
```
[the remark this answers is not in the document]
Comment (Williangalvani) [reply core/frontend/src/utils/helper_functions.ts:21]: it cannot. member functions return "" instead of the function name, that was my first attempt =[
I even throwed an error for anonymous functions

File: core/frontend/src/utils/helper_functions.ts [hunk 2]
```diff
@@ -6,15 +6,37 @@ export function sleep(interval: number): Promise<void> {
...
+}
+
+/* Stop Callingg a given function periodically. */
+/**
+ * @param function_name - Function to be called.
+* */
+export function stopCallingPeriodically(func: () => Promise<void>): void {
+  const current_count = periodic_tasks_counter.get(func) ?? 1
+  periodic_tasks_counter.set(func, current_count - 1)
+  console.log(periodic_tasks_counter)
```
Comment (patrickelectric) [inline core/frontend/src/utils/helper_functions.ts:39]: Remove debug message

File: core/frontend/src/utils/helper_functions.ts [hunk 3]
```diff
@@ -6,15 +6,37 @@ export function sleep(interval: number): Promise<void> {
...
-export async function callPeriodically(func: () => Promise<void>, interval: number): Promise<void> {
+export async function callPeriodically(
+  func: () => Promise<void>, interval: number, automated_call?: boolean,
+): Promise<void> {
+  let current_count = periodic_tasks_counter.get(func) ?? 0
+  if (!automated_call) {
+    current_count += 1
+    periodic_tasks_counter.set(func, current_count + 1)
+  }
+  if (current_count <= 0) {
```
Comment (patrickelectric) [inline core/frontend/src/utils/helper_functions.ts:24]: Should we set current count to 0 ?

**Review by patrickelectric — CHANGES_REQUESTED** [review]
