### PR TITLE
Fix beacon frontend

### LINKED ISSUE #1809: Frontend interface for beacon is not reflecting changes in the backend
image
image
image

### PR DESCRIPTION
**Pull request by joaoantoniocardoso**
Closes #1809

### CODE REVIEW

File: core/frontend/src/store/beacon.ts [hunk 1]
```diff
@@ -33,7 +33,7 @@ class BeaconStore extends VuexModule {
 
   nginx_ip_address = ''
 
-  hostname: undefined | string = undefined
+  hostname = ''
```
Comment (patrickelectric) [inline core/frontend/src/store/beacon.ts:36]: why is this an empty string ? with that there is no way for us to check if the value was proper set/valid or not.

Comment (joaoantoniocardoso) [reply core/frontend/src/store/beacon.ts:36]: How is this different from the other properties?

Comment (patrickelectric) [reply core/frontend/src/store/beacon.ts:36]: Well for IP consistency it makes sense.. but for valid check empty string is not the proper way.

**Review by patrickelectric — APPROVED** [review]
