### PR TITLE
Fix sdp

### LINKED ISSUE #1483: Expose the SDP download link

### LINKED ISSUE #1488: bug: video manager: SDP generation fails for Fake Source
### Bug description

Console error:
```js
ERR_ACTION_ACCESS_UNDEFINED: Are you trying to access this.someMutation() or this.someGetter inside an @Action? 
That works only in dynamic modules. 
If not dynamic use this.context.commit("mutationName", payload) and this.context.getters["getterName"]
Error: Could not perform action fetchSDP
    at w.<anonymous> (http://blueos.local/js/chunk-vendors.909fdb08.js:1154:5439)
    at l (http://blueos.local/js/chunk-vendors.909fdb08.js:1154:1360)
    at Object.throw (http://blueos.local/js/chunk-vendors.909fdb08.js:1154:655)
    at o (http://blueos.local/js/chunk-vendors.909fdb08.js:1154:284)
TypeError: Cannot read properties of undefined (reading 'device_path')
    at Object.fetchSDP (http://blueos.local/js/app.6ca3e066.js:1:2558516)
    at w.<anonymous> (http://blueos.local/js/chunk-vendors.909fdb08.js:1154:4956)
    at l (http://blueos.local/js/chunk-vendors.909fdb08.js:1154:1360)
    at Object.next (http://blueos.local/js/chunk-vendors.909fdb08.js:1154:655)
    at http://blueos.local/js/chunk-vendors.909fdb08.js:1154:380
    at new Promise (<anonymous>)
    at c (http://blueos.local/js/chunk-vendors.909fdb08.js:1154:173)
    at w.d (http://blueos.local/js/chunk-vendors.909fdb08.js:1154:4744)
    at Array.<anonymous> (http://blueos.local/js/chunk-vendors.909fdb08.js:1170:6406)
    at w.dispatch (http://blueos.local/js/chunk-vendors.909fdb08.js:1170:7741)
    at w.<anonymous> (http://blueos.local/js/chunk-vendors.909fdb08.js:1154:5170)
    at l (http://blueos.local/js/chunk-vendors.909fdb08.js:1154:1360)
    at Object.throw (http://blueos.local/js/chunk-vendors.909fdb08.js:1154:655)
    at o (http://blueos.local/js/chunk-vendors.909fdb08.js:1154:284)
re @ vue.runtime.esm.js:1897
```

### Steps to reproduce

1. Open "Video Streams" page
2. Create a UDP stream Fake Source (in Pirate Mode)
3. Attempt to download the SDP file
4. Nothing happens

### Primary pain point(s)

Makes it harder to test functionality. Not critical, since the Fake Source is only used for testing purposes.

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

### PR DESCRIPTION
**Pull request by joaoantoniocardoso**
Closes #1483 and fixes #1488 

# Before:

image

# After:

image

### CODE REVIEW

**Review by patrickelectric — APPROVED** [review]

File: core/frontend/src/components/video-manager/VideoStream.vue [hunk 1]
```diff
@@ -20,60 +15,43 @@
...
+        </v-simple-table>
+        <div v-if="isSDPFileAvailable" class="ma-2 justify-space-between">
+          SDP file:
+          <v-btn v-tooltip="'Download to file'" class="ma-1 elevation-1" small @click="downloadSDPFile">
             <v-icon>mdi-download</v-icon>
-            SDP
           </v-btn>
-        </template>
-      </v-simple-table>
+          <v-btn v-tooltip="'Copy to clipboard'" class="ma-1 elevation-1" small @click="copySDPFileURL">
```
Comment (patrickelectric) [inline core/frontend/src/components/video-manager/VideoStream.vue:41]: `Copy file URL to clipboard`

Comment (joaoantoniocardoso) [reply core/frontend/src/components/video-manager/VideoStream.vue:41]: True, it's not clear if it's the URL or the file content that would be copied. Maybe also change the icon to this one?

image

**Comment by patrickelectric** [comment]
Looks better
