### PR TITLE
components: health: Fix heartbeat icon to use only vehicle heartbeat

### LINKED ISSUE #838: bug: Hearbeat icon beating fine when only a camera is alive
### Bug description

image

image

### Steps to reproduce

1. Upgrade Navigator firmware to Dev (which is broken)
2. Ardupilot-manager will fail to start the firmware and enter a restart loop
3. Watch the heartbit icon and Mavlink inspector

### Primary pain point(s)

User thinks everything is fine when it isn't.

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

### PR DESCRIPTION
**Pull request by patrickelectric**
Fix #838 

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

File: core/frontend/src/components/health/HealthTrayMenu.vue [hunk 1]
```diff
@@ -143,12 +149,20 @@ export default Vue.extend({
...
+    heartbeat_age(): number | undefined {
+      const heartbeat = mavlink_store_get(mavlink, 'HEARTBEAT') as MavlinkMessage
+      const last_date = heartbeat.timestamp
       if (last_date === undefined) {
-        return 5000
+        this.last_date_diff = 5000
+        return this.last_date_diff
+      }
+
+      if (heartbeat?.messageData.header.system_id !== 1 && heartbeat?.messageData.header.component_id !== 1) {
```
Comment (rafaellehmkuhl) [inline core/frontend/src/components/health/HealthTrayMenu.vue:160]: Shouldn't it be `if x or y`? As I understand a vehicle has both system id and component id equal to 1, right?

**Review by rafaellehmkuhl — CHANGES_REQUESTED** [review]

File: core/frontend/src/components/health/HealthTrayMenu.vue (hunk 1 above)
Comment (patrickelectric) [reply core/frontend/src/components/health/HealthTrayMenu.vue:160]: Yep

Comment (patrickelectric) [reply core/frontend/src/components/health/HealthTrayMenu.vue]: good catch, fixed!

**Review by Williangalvani — APPROVED** [review]
