### PR TITLE
core: components: parameter-editor: Fix display of bitmask values

### LINKED ISSUE #1234: bug: Some parameters appears as numbers and not as flags names on the UI
### Bug description

image

### Steps to reproduce

Check LOG_BACKEND_TYPE on the parameter editor

### Primary pain point(s)

It's not friendly which options are on

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

### PR DESCRIPTION
**Pull request by patrickelectric**
Fix #1234 

image

image

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Review by Williangalvani — CHANGES_REQUESTED** [review]
We should also handle cases where bits not available in the metadata are set.
we could show each of them as an unkown entry?
"OPTION, OPTION2 , Bit 4, Bit 8". Idk.

**Comment by patrickelectric** [comment]
> We should also handle cases where bits not available in the metadata are set. we could show each of them as an unkown entry? "OPTION, OPTION2 , Bit 4, Bit 8". Idk.

Done.

File: core/frontend/src/components/parameter-editor/ParameterEditor.vue [hunk 1]
```diff
@@ -309,10 +311,29 @@ export default Vue.extend({
...
+      if (param.bitmask) {
+        const bitmask_result = []
+        // We check up to 64 bits to make sure that we are going to cover all possible bits
+        // Including the ones not listed in the bitmask
+        for (let v = 0; v < 64; v += 1) {
+          // eslint-disable-next-line no-bitwise
+          const bitmask_value = 1 << v
+          // eslint-disable-next-line no-bitwise
+          if (param.value & bitmask_value) {
+            bitmask_result.push(param.bitmask?.[v] ?? `Bit ${v + 1}`)
```
Comment (ES-Alexander) [inline core/frontend/src/components/parameter-editor/ParameterEditor.vue:331]: This could be ok as is, but if someone doesn't know what a bitmask is (just that the parameter has multiple options) it may be worth being more explicit that the value is unknown, not just what it is. Maybe something like
- `UNKNOWN (bit #)`
- `UNKNOWN(#)`
- `Unknown:#`
- `? (bit #)`

Comment (patrickelectric) [reply core/frontend/src/components/parameter-editor/ParameterEditor.vue]: Done.

**Review by Williangalvani — APPROVED** [review]
